# Generated by Django 5.0.4 on 2024-06-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='designation',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='disease_type',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='age',
        ),
        migrations.AddField(
            model_name='doctor',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(default='null', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], max_length=10),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='certification',
            field=models.CharField(max_length=100),
        ),
    ]
