# Generated by Django 5.0.4 on 2024-06-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_designation_doctor_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
    ]
