# Generated by Django 5.0.4 on 2024-06-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_doctor_certification_remove_doctor_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_images/'),
        ),
    ]
