# Generated by Django 5.0.4 on 2024-06-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_doctor_image_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='image_upload',
            new_name='img',
        ),
    ]
